name: Run E2E Test Cases

on:
  workflow_dispatch:  # This makes it run only when manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: grovecai0108/dataflow-e2e-runner
      options: --user root  # Run as root to ensure permissions

    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y sudo
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Change ownership and permissions
        run: |
          pwd;
          ls -al;
          cp -R $GITHUB_WORKSPACE /home/pptruser
          chown -R pptruser:pptruser /home/pptruser/gaction
          chmod -R 777 /home/pptruser/gaction

      - name: Debug workspace permissions
        run: ls -ld /home/pptruser/gaction
        
      - name: Switch to pptruser with ENV2
        run: sudo -u pptruser bash -c "whoami && export GOROOT=/home/pptruser/go && export GOPATH=/home/pptruser/gopath && export PATH=/home/pptruser/go/bin:/home/pptruser/gopath/bin:\$PATH && env && make all && pwd && node ../login.js 'https://dev.tidbcloud.com' 'xxx' 'xxx' '../'"


      - name: Switch to pptruser with ENV
        run: |
           sudo -E -u pptruser bash -c "whoami && env && echo $PATH && pwd && cd /home/pptruser/gaction && make all && node ../login.js 'https://dev.tidbcloud.com' 'xxx' 'xxx' '../'"
          
      - name: Switch to pptruser and execute commands
        run: |
          env;
          echo $PATH
          sudo -u pptruser bash -c "whoami && node -v && export GOROOT=/home/pptruser/go && export GOPATH=/home/pptruser/gopath && export PATH=/home/pptruser/go/bin:/home/pptruser/gopath/bin:${PATH} && make all && node ../login.js 'https://dev.tidbcloud.com' 'xxx' 'xxx' '../'"

      - name: Run E2E
        run: |
          whoami;
          cd /home/pptruser/gaction;
          node -v;
          go version;
          make all;
          node ../login.js "https://dev.tidbcloud.com" "xxx" "xxx" "../";
