name: Run E2E Test Cases

on:
  workflow_dispatch:  # This makes it run only when manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: grovecai0108/dataflow-e2e-runner
      options: --user pptruser  # Run as root to ensure permissions

    steps:
      - name: Debug workspace permissions
        run: ls -ld $GITHUB_WORKSPACE && cd /home/pptruser && ls -al
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug workspace permissions
        run: ls -ld $GITHUB_WORKSPACE

      - name: Run E2E
        run: |
          make all;
          node ../login.js "https://dev.tidbcloud.com" "xxx" "xxx" "../";
