name: Run E2E Test Cases as Root

on:
  workflow_dispatch:  # This makes it run only when manually triggered
    inputs:
      env:
        description: "Cases environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      case_group:
        description: "Select case group to be run"
        required: false
        default: "smoke"
        type: choice
        options:
          - smoke
          - awsSmoke
          - gcpSmoke
          - azureSmoke
          - all
          - awsAll
          - gcpAll
          - azureAll
      cases:
        description: "Run specific cases(separated by ',', if not empty cases in case_group will be ignored"
        required: false
        type: string
      auth_token:
        description: "Bear token(please copy token here without 'Bear' prefix)."
        required: true
        type: string
      aws_regions:
        description: "AWS regions for aws cases to run. Most cases only need one, some need two."
        required: false
        default: "us-west-2,us-west-1"
        type: string
      gcp_regions:
        description: "GCP regions for gcp cases to run. Most cases only need one, some need two."
        required: false
        default: "us-west1,us-west2"
        type: string
      azure_regions:
        description: "Azure regions for azure cases to run. Most cases only need one, some need two."
        required: false
        default: "eastus"
        type: string

      org_id:
        description: "Org id for specific org instead of default"
        required: false
        type: string
      project_id:
        description: "Project id specific project instead of default"
        required: false
        type: string
      cluster_ids:
        description: "Cluster ids for reusing existed clusters(separated by ',')"
        required: false
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: grovecai0108/dataflow-e2e-runner:1.0
      options: --user root  # Run as root to ensure permissions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run  
        run: |
          whoami;
          node -v;
          go version;
          make all;
          cd /home/pptruser;
          node login.js "https://dev.tidbcloud.com" "xxx" "xxx" "../";
